/* ============================================================
   matrixos-app.jsx — Matrix OS · Admin Command Center
   Faithful reproduction of the MatrixOS.html design, wired to live
   matrix-os data via ./data.json (generated by `matrix-os dashboard`).
   Every live field falls back to the built-in demo content when absent.
   ============================================================ */
const { OI, O, Logo } = window.MOS;

const NAV = [
  { id: "overview", label: "Overview", ic: O.grid },
  { id: "catalog", label: "Catalog", ic: O.db, tag: "2.4K" },
  { id: "planner", label: "Planner", ic: O.spark },
  { id: "runtime", label: "Runtime", ic: O.play, tag: "6" },
  { id: "memory", label: "Memory", ic: O.brain },
  { id: "coder", label: "AI Coder", ic: O.flow, tag: "PR" },
  { id: "governance", label: "Governance", ic: O.shield },
  { id: "system", label: "System", ic: O.wrench },
];

/* metric icons are string keys so data.json can drive them */
const METRICS = [
  { label: "Indexed Entities", value: "2,481", delta: "+142 from last sync", ic: "db", tone: "blue" },
  { label: "Active Workflows", value: "46", delta: "+8 from yesterday", ic: "flow", tone: "violet" },
  { label: "Memory Recall", value: "92.4%", delta: "+3.7pp citation faithful", ic: "brain", tone: "cyan" },
  { label: "Governance Health", value: "98.7%", delta: "0 open incidents", ic: "shield", tone: "green" },
];

const AGENTS = [
  ["Researcher Pro", "Research", "Online", "320 ms"],
  ["DataAnalyst", "Analysis", "Online", "210 ms"],
  ["ContentGen", "Generation", "Online", "290 ms"],
  ["Guardian", "Safety", "Online", "180 ms"],
  ["CodeAgent", "Development", "Online", "260 ms"],
];

const WORKFLOWS = [
  ["Customer Onboarding Flow", "Completed", "2m ago", "green"],
  ["Market Research Pipeline", "Completed", "14m ago", "green"],
  ["Invoice Processing v3", "Running", "22m ago", "blue"],
  ["Data Sync & Validation", "Failed", "45m ago", "red"],
  ["Weekly Compliance Report", "Completed", "1h ago", "green"],
];

const EVENTS = [
  ["Policy violation blocked in workflow ‘Vendor Sync’", "12m ago"],
  ["Guardian approved deployment request for agent ‘Maintainer’", "21m ago"],
  ["Memory consolidation completed for project ‘Matrix OS’", "35m ago"],
  ["Runtime region eu-west-1 recovered successfully", "56m ago"],
];

const SYSTEM = [["System Uptime", "99.98%"], ["Runtime Regions", "6"], ["Active Users", "24"], ["Open Incidents", "0"]];

const NODES = [
  { x: 17, y: 24, ic: O.spark, t: "Matrix AI", s: "Planner", tone: "cyan" },
  { x: 16, y: 76, ic: O.brain, t: "Matrix Context", s: "Memory", tone: "violet" },
  { x: 50, y: 50, ic: O.play, t: "Matrix Runtime", s: "Execution kernel", tone: "green", large: true },
  { x: 50, y: 14, ic: O.shield, t: "Matrix Guardian", s: "Governance", tone: "amber" },
  { x: 83, y: 24, ic: O.db, t: "Matrix Hub", s: "Discovery", tone: "blue" },
  { x: 84, y: 76, ic: O.cpu, t: "Matrix LLM", s: "Model router", tone: "blue" },
];
/* hub-and-spoke: every node links to Runtime (center) */
const EDGE_TONES = ["var(--cyan)", "var(--violet)", "var(--amber)", "var(--blue)", "var(--blue)"];

/* fetch the live snapshot once; null until loaded / on failure */
function useLiveData() {
  const [d, setD] = React.useState(null);
  React.useEffect(() => {
    let on = true;
    fetch("data.json", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : null))
      .then((j) => { if (on && j) setD(j); })
      .catch(() => {});
    return () => { on = false; };
  }, []);
  return d;
}
const nonEmpty = (a) => Array.isArray(a) && a.length > 0;

function Panel({ title, link, onLink, children, style }) {
  return (
    <section className="panel" style={style}>
      <div className="panel-h">
        <h3>{title}</h3>
        {link && <button className="panel-link" onClick={onLink}>{link}</button>}
      </div>
      {children}
    </section>
  );
}

function Topology() {
  const hub = NODES.find((n) => n.large);
  const spokes = NODES.filter((n) => !n.large);
  return (
    <section className="panel rise" style={{ position: "relative", overflow: "hidden" }}>
      <div className="panel-h">
        <h3>System Orchestration</h3>
        <span className="chip green"><span className="dot green pulse" /> Live Topology</span>
      </div>
      <div className="topo">
        <div className="grid" />
        <svg className="topo-svg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
          <defs>
            {spokes.map((n, i) => (
              <linearGradient key={i} id={"edge" + i} x1={n.x + "%"} y1={n.y + "%"} x2={hub.x + "%"} y2={hub.y + "%"} gradientUnits="userSpaceOnUse">
                <stop offset="0%" stopColor={EDGE_TONES[i]} stopOpacity="0.15" />
                <stop offset="100%" stopColor="var(--blue)" stopOpacity="0.85" />
              </linearGradient>
            ))}
          </defs>
          {spokes.map((n, i) => (
            <line key={i} x1={n.x} y1={n.y} x2={hub.x} y2={hub.y} stroke={"url(#edge" + i + ")"} strokeWidth="0.4" vectorEffect="non-scaling-stroke"
              className="topo-edge" style={{ animationDelay: (i * 0.3) + "s" }} />
          ))}
        </svg>
        {spokes.map((n, i) => (
          <span key={i} className="topo-pulse" style={{ left: n.x + "%", top: n.y + "%",
            "--tx": (hub.x - n.x) + "%", "--ty": (hub.y - n.y) + "%", animationDelay: (i * 0.5) + "s",
            background: EDGE_TONES[i] }} />
        ))}
        {NODES.map((n) => (
          <div key={n.t} className={"node" + (n.large ? " large" : "")} style={{ left: n.x + "%", top: n.y + "%", transform: "translate(-50%, -50%)" }}>
            <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
              <span className={"ni tone-" + n.tone}><OI d={n.ic} size={18} /></span>
              <div><div className="nt">{n.t}</div><div className="ns">{n.s}</div></div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function SidebarAccount({ go }) {
  const [open, setOpen] = React.useState(false);
  const items = [
    { label: "Personalization", ic: O.sliders, fn: () => go("system") },
    { label: "Profile", ic: O.badge, fn: () => go("system") },
    { label: "Settings", ic: O.wrench, fn: () => go("system") },
  ];
  return (
    <div style={{ position: "relative" }}>
      {open && (
        <React.Fragment>
          <div style={{ position: "fixed", inset: 0, zIndex: 44 }} onClick={() => setOpen(false)} />
          <div className="acct-menu rise" style={{ position: "absolute", bottom: "calc(100% + 10px)", left: 0, right: 0, zIndex: 45 }}>
            <div className="acct-head">
              <span className="av"><OI d={O.user} size={22} /></span>
              <div style={{ minWidth: 0 }}>
                <div style={{ fontSize: 13.5, fontWeight: 600, color: "var(--ink)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>Ruslan Magana Vsevolodovna</div>
                <div style={{ fontSize: 11.5, color: "var(--ink-4)" }}>Plus</div>
              </div>
              <OI d={O.chevr} size={15} style={{ color: "var(--ink-4)", transform: "rotate(-90deg)", flexShrink: 0 }} />
            </div>
            <div className="acct-div" />
            {items.map((it) => (
              <button key={it.label} className="acct-item" onClick={() => { setOpen(false); it.fn(); }}>
                <span className="i"><OI d={it.ic} size={17} /></span> {it.label}
              </button>
            ))}
            <div className="acct-div" />
            <button className="acct-item" onClick={() => setOpen(false)}>
              <span className="i"><OI d={O.help} size={17} /></span> <span style={{ flex: 1, textAlign: "left" }}>Help</span>
              <OI d={O.chevr} size={14} style={{ color: "var(--ink-4)" }} />
            </button>
            <button className="acct-item" onClick={() => setOpen(false)}>
              <span className="i"><OI d={O.logout} size={17} /></span> Log out
            </button>
          </div>
        </React.Fragment>
      )}
      <button className={"user-card" + (open ? " open" : "")} onClick={() => setOpen((v) => !v)} aria-label="Account menu" style={{ width: "100%", cursor: "pointer" }}>
        <span className="av"><OI d={O.user} size={24} /></span>
        <div style={{ minWidth: 0, flex: 1, textAlign: "left" }}>
          <div style={{ fontSize: 13.5, fontWeight: 600, color: "var(--ink)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>Ruslan Magana Vsevolodovna</div>
          <div style={{ fontSize: 11.5, color: "var(--ink-4)" }}>Plus</div>
        </div>
        <OI d={O.chevr} size={16} style={{ color: "var(--ink-4)", transform: "rotate(-90deg)", flexShrink: 0 }} />
      </button>
    </div>
  );
}

function App() {
  const [route, setRoute] = React.useState("overview");
  const [sideOpen, setSideOpen] = React.useState(false);
  const [anim, setAnim] = React.useState(() => { try { return localStorage.getItem("mos-anim") !== "off"; } catch (e) { return true; } });
  const live = useLiveData();
  const data = {
    metrics: nonEmpty(live && live.metrics) ? live.metrics : METRICS,
    workflows: nonEmpty(live && live.workflows) ? live.workflows : WORKFLOWS,
    events: nonEmpty(live && live.events) ? live.events : EVENTS,
    agents: nonEmpty(live && live.agents) ? live.agents : AGENTS,
    system: nonEmpty(live && live.system) ? live.system : SYSTEM,
    coderTask: (live && live.coder_task) || null,
  };
  const label = (NAV.find((n) => n.id === route) || {}).label || "Overview";
  function go(id) { setRoute(id); setSideOpen(false); }
  React.useEffect(() => {
    document.documentElement.classList.toggle("mos-no-anim", !anim);
    try { localStorage.setItem("mos-anim", anim ? "on" : "off"); } catch (e) {}
  }, [anim]);

  return (
    <div className="shell">
      {sideOpen && <div className="side-scrim" onClick={() => setSideOpen(false)} />}
      <aside className={"side" + (sideOpen ? " open" : "")}>
        <div className="brand">
          <span className="logo"><Logo size={26} /></span>
          <div><div className="nm">Matrix OS</div><div className="sub">Admin Console</div></div>
        </div>
        <nav className="nav">
          {NAV.map((n) => (
            <button key={n.id} className={"navitem" + (route === n.id ? " active" : "")} onClick={() => go(n.id)}>
              <span className="l"><span className="i"><OI d={n.ic} size={18} /></span> {n.label}</span>
              {route === n.id ? <OI d={O.chevr} size={16} style={{ color: "var(--cyan)" }} /> : (n.tag && <span className="tag">{n.tag}</span>)}
            </button>
          ))}
        </nav>
        <div className="side-foot">
          <SidebarAccount go={go} />
        </div>
      </aside>

      <div className="main">
        <header className="top">
          <div className="top-in">
            <div style={{ display: "flex", alignItems: "center", gap: 14, flex: 1, minWidth: 0 }}>
              <button className="iconbtn menu-btn" onClick={() => setSideOpen(true)}><OI d={O.menu} size={18} /></button>
              <div className="search">
                <OI d={O.search} size={17} />
                <input placeholder="Search agents, workflows, memory, docs…" />
              </div>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <span className="statuspill"><span className="dot green pulse" /> system online</span>
              <button className="iconbtn hide-sm"><OI d={O.bell} size={17} /></button>
              <button className="deploy"><OI d={O.rocket} size={17} /> <span className="hide-sm">Deploy</span></button>
            </div>
          </div>
        </header>

        <div className="wrap">
          <div className="wrapin" key={route}>
            <div className="rise">
              <p className="eyebrow">Current module</p>
              <h1 style={{ margin: "8px 0 0", fontSize: 34, fontWeight: 600, letterSpacing: "-0.03em" }}>{label}</h1>
            </div>

            {route === "overview" ? <Overview go={go} data={data} /> : route === "coder" ? <CoderView data={data} /> : route === "system" ? <SystemView anim={anim} setAnim={setAnim} /> : <Placeholder label={label} go={go} />}
          </div>
        </div>
      </div>
    </div>
  );
}

function Overview({ go, data }) {
  return (
    <React.Fragment>
      <div className="metrics rise">
        {data.metrics.map((m) => (
          <div className="metric" key={m.label}>
            <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between" }}>
              <span className={"ico tone-" + m.tone}><OI d={O[m.ic] || O.grid} size={20} /></span>
              <span className="live">Live</span>
            </div>
            <div className="lab">{m.label}</div>
            <div className="val">{m.value}</div>
            <div className="delta">{m.delta}</div>
          </div>
        ))}
      </div>

      <div className="os-cols rise" style={{ display: "grid", gridTemplateColumns: "1.65fr 1fr", gap: 22 }}>
        <Topology />
        <div style={{ display: "flex", flexDirection: "column", gap: 22 }}>
          <Panel title="Recent Workflows" link="View all" onLink={() => go("workflows")}>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {data.workflows.slice(0, 4).map((w) => (
                <div className="lrow" key={w[0]}>
                  <div style={{ display: "flex", gap: 11 }}>
                    <span className={"dot " + w[3]} style={{ marginTop: 5 }} />
                    <div><div style={{ fontSize: 13.5, fontWeight: 500, color: "var(--ink)" }}>{w[0]}</div>
                      <div className="mono" style={{ fontSize: 11, color: "var(--ink-4)", marginTop: 3 }}>wf_93d…f2a7</div></div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 13, fontWeight: 500, color: w[3] === "green" ? "#6ee7a0" : w[3] === "blue" ? "var(--blue-2)" : "#ff8585" }}>{w[1]}</div>
                    <div style={{ fontSize: 11, color: "var(--ink-4)", marginTop: 3 }}>{w[2]}</div>
                  </div>
                </div>
              ))}
            </div>
          </Panel>
          <Panel title="Recent Events" link="View all" onLink={() => go("system")}>
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
              {data.events.map((e) => (
                <div className="lrow" key={e[0]}>
                  <div style={{ display: "flex", gap: 11 }}>
                    <span style={{ color: "var(--cyan)", display: "inline-flex", marginTop: 1 }}><OI d={O.scroll} size={16} /></span>
                    <div style={{ minWidth: 0 }}><div style={{ fontSize: 13, color: "var(--ink)", lineHeight: 1.5 }}>{e[0]}</div>
                      <div style={{ fontSize: 11, color: "var(--ink-4)", marginTop: 4 }}>{e[1]}</div></div>
                  </div>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      </div>

      <div className="os-cols3 rise" style={{ display: "grid", gridTemplateColumns: "1.3fr 1fr 0.8fr", gap: 22 }}>
        <Panel title="Agent Status" link="View all" onLink={() => go("agents")}>
          <div className="tbl-wrap">
            <table className="tbl">
              <thead><tr><th>Agent</th><th>Role</th><th>Status</th><th>Latency</th></tr></thead>
              <tbody>
                {data.agents.map((a) => (
                  <tr key={a[0]}><td className="nm">{a[0]}</td><td>{a[1]}</td>
                    <td><span style={{ display: "inline-flex", alignItems: "center", gap: 7, color: "#6ee7a0" }}><span className="dot green" /> {a[2]}</span></td>
                    <td className="mono" style={{ fontSize: 12 }}>{a[3]}</td></tr>
                ))}
              </tbody>
            </table>
          </div>
        </Panel>

        <Panel title="Memory" link="Inspect" onLink={() => go("memory")}>
          <div style={{ display: "flex", flexDirection: "column", gap: 11 }}>
            {[["Semantic recall", "94.2%", "cyan"], ["Episodic recall", "90.6%", "violet"], ["Expert routing", "97.1%", "green"]].map(([k, v, t]) => (
              <div key={k}>
                <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12.5, marginBottom: 7 }}><span style={{ color: "var(--ink-3)" }}>{k}</span><span className="mono" style={{ color: "var(--ink)" }}>{v}</span></div>
                <div style={{ height: 6, borderRadius: 99, background: "var(--inset)", overflow: "hidden" }}><span style={{ display: "block", height: "100%", width: v, background: "var(--" + t + ")", borderRadius: 99 }} /></div>
              </div>
            ))}
            <div style={{ marginTop: 6, padding: 14, borderRadius: "var(--r-md)", border: "1px solid var(--cyan-line)", background: "var(--cyan-soft)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--cyan)", fontSize: 13, fontWeight: 600 }}><OI d={O.brain} size={15} /> Consolidation healthy</div>
              <p style={{ margin: "7px 0 0", fontSize: 12, lineHeight: 1.55, color: "var(--ink-3)" }}>Memory layers synced across regions. No recall degradation detected.</p>
            </div>
          </div>
        </Panel>

        <Panel title="System Summary">
          <div style={{ display: "flex", flexDirection: "column", gap: 11 }}>
            {data.system.map(([k, v]) => (
              <div key={k} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "13px 15px", borderRadius: "var(--r-md)", border: "1px solid var(--line)", background: "rgba(255,255,255,0.02)" }}>
                <span style={{ fontSize: 13, color: "var(--ink-3)" }}>{k}</span><span style={{ fontSize: 17, fontWeight: 600, color: "var(--ink)" }}>{v}</span>
              </div>
            ))}
            <div style={{ marginTop: 4, padding: 14, borderRadius: "var(--r-md)", border: "1px solid var(--green-line)", background: "var(--green-soft)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, color: "#6ee7a0", fontSize: 13, fontWeight: 600 }}><OI d={O.gauge} size={15} /> Runtime stable</div>
              <p style={{ margin: "7px 0 0", fontSize: 12, lineHeight: 1.55, color: "var(--ink-3)" }}>All core services healthy. Governance checks within normal range.</p>
            </div>
          </div>
        </Panel>
      </div>
    </React.Fragment>
  );
}

function SystemView({ anim, setAnim }) {
  const [reduceGlow, setReduceGlow] = React.useState(false);
  const [compact, setCompact] = React.useState(false);
  const settings = [
    { k: "UI animations", d: "Topology pulses, entrance transitions, and live indicators.", on: anim, set: setAnim, primary: true },
    { k: "Reduce ambient glow", d: "Lower the background radial glow for a flatter surface.", on: reduceGlow, set: setReduceGlow },
    { k: "Compact density", d: "Tighter spacing across tables and panels.", on: compact, set: setCompact },
  ];
  const env = [["RUNTIME_MODE", "HYBRID"], ["REGIONS", "6 active"], ["GOVERNANCE", "ENFORCED"], ["AUTH_MODE", "LOCAL_ADMIN"], ["VERSION", "matrix-os 1.0.0"]];
  return (
    <div className="os-cols rise" style={{ display: "grid", gridTemplateColumns: "1.05fr 0.95fr", gap: 22 }}>
      <Panel title="Appearance">
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {settings.map((s) => (
            <div className="setrow" key={s.k}>
              <div style={{ minWidth: 0 }}>
                <div style={{ fontSize: 14, fontWeight: 600, color: "var(--ink)" }}>{s.k}</div>
                <div style={{ fontSize: 12.5, color: "var(--ink-3)", marginTop: 3, lineHeight: 1.5 }}>{s.d}</div>
              </div>
              <button className={"tgl" + (s.on ? " on" : "")} onClick={() => s.set(!s.on)} role="switch" aria-checked={s.on} aria-label={s.k}><span /></button>
            </div>
          ))}
          <div style={{ marginTop: 4, padding: 14, borderRadius: "var(--r-md)", border: "1px solid var(--blue-line)", background: "var(--blue-soft)" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--blue-2)", fontSize: 13, fontWeight: 600 }}><OI d={O.spark} size={15} /> {anim ? "Premium motion enabled" : "Motion disabled"}</div>
            <p style={{ margin: "7px 0 0", fontSize: 12, lineHeight: 1.55, color: "var(--ink-3)" }}>{anim ? "Live topology and indicators animate. Best for demos and command-center displays." : "All UI animations are off for a calm, static, low-distraction surface."}</p>
          </div>
        </div>
      </Panel>
      <Panel title="Environment">
        <div style={{ display: "flex", flexDirection: "column", gap: 11 }}>
          {env.map(([k, v]) => (
            <div key={k} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "13px 15px", borderRadius: "var(--r-md)", border: "1px solid var(--line)", background: "rgba(255,255,255,0.02)" }}>
              <span className="mono" style={{ fontSize: 12.5, color: "var(--ink-4)", letterSpacing: "0.04em" }}>{k}</span>
              <span className="mono" style={{ fontSize: 12.5, color: "var(--blue-2)" }}>{v}</span>
            </div>
          ))}
        </div>
      </Panel>
    </div>
  );
}

function CoderTabs({ active, set }) {
  const tabs = [["pipeline", "Pipeline"], ["changes", "Changes"], ["approval", "Approval"], ["evidence", "Evidence"], ["autonomy", "Autonomy"]];
  return (
    <div style={{ display: "flex", gap: 4, padding: 4, borderRadius: 99, border: "1px solid var(--line)", background: "rgba(0,0,0,0.25)", marginBottom: 22, flexWrap: "wrap" }}>
      {tabs.map(([id, label]) => (
        <button key={id} onClick={() => set(id)} style={{ flex: "1 1 auto", height: 38, padding: "0 16px", borderRadius: 99, fontSize: 13.5, fontWeight: 600,
          background: active === id ? "var(--blue-soft)" : "transparent", color: active === id ? "var(--blue-2)" : "var(--ink-3)",
          border: "1px solid " + (active === id ? "var(--blue-line)" : "transparent"), transition: "all .13s" }}>{label}</button>
      ))}
    </div>
  );
}

function CoderView({ data }) {
  const [tab, setTab] = React.useState("pipeline");
  const task = (data && data.coderTask) || {};
  const title = task.title || "Fix failing dependency update in matrix-runtime";
  const repo = task.repo || "agent-matrix/matrix-runtime · branch ai/fix-runtime-healthcheck";
  const coderName = task.coder || "GitPilot (default)";
  const risk = task.risk || "Medium";
  const mode = task.mode || "dry_run";
  const stages = [
    { k: "Explore", o: "Explorer", st: "done", ic: O.search, m: "code-fast · repo read" },
    { k: "Plan", o: "Planner", st: "done", ic: O.spark, m: "repair-plan · 4 issues" },
    { k: "Approve", o: "Guardian", st: "active", ic: O.shield, m: "Risk Med · paths gated" },
    { k: "Code", o: "Coder", st: "todo", ic: O.play, m: "code-coder · diff" },
    { k: "Review", o: "Reviewer", st: "todo", ic: O.badge, m: "code-reviewer + MatrixLab" },
  ];
  const diff = [
    ["matrix-runtime/internal/health.go", "modified", "blue"],
    ["deploy/compose/healthcheck.yaml", "modified", "blue"],
    ["tests/test_healthcheck.py", "added", "green"],
    ["README.md", "modified", "blue"],
  ];
  const rollout = [
    ["Observe Only", "Read-only plan generation", "Active", "green", ""],
    ["Suggest Patch", "Sandboxed patch proposals", "Active", "green", ""],
    ["Open PR", "Bot opens PRs (low-risk)", "Current", "amber", "this run"],
    ["Limited Autopilot", "Auto-merge allowlist", "Locked", "red", "needs 30 clean PR runs"],
    ["Supervised Feature Work", "Bounded feature patches", "Locked", "red", "security sign-off required"],
  ];
  const evidence = [
    ["plan-ir", "captured"], ["tool logs", "captured"], ["diff", "4 files changed"],
    ["unit tests", "128 passed"], ["secret scan", "clean"], ["policy report", "passed"],
    ["rollback plan", "ready"], ["approval ticket", "pending"],
  ];
  return (
    <React.Fragment>
      <div className="panel rise" style={{ marginBottom: 22 }}>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 16, alignItems: "flex-start", justifyContent: "space-between" }}>
          <div style={{ display: "flex", gap: 14, minWidth: 0 }}>
            <span className="ico tone-amber" style={{ width: 46, height: 46, borderRadius: 14, display: "grid", placeItems: "center", border: "1px solid var(--amber-line)", background: "var(--amber-soft)", color: "#fbbf4d", flexShrink: 0 }}><OI d={O.flow} size={22} /></span>
            <div style={{ minWidth: 0 }}>
              <p className="eyebrow" style={{ color: "rgba(245,197,66,0.7)" }}>Current task</p>
              <h2 style={{ margin: "7px 0 0", fontSize: 21, fontWeight: 600, letterSpacing: "-0.02em" }}>{title}</h2>
              <div className="mono" style={{ marginTop: 8, fontSize: 12, color: "var(--ink-3)" }}>{repo}</div>
            </div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 10 }}>
            <span className="chip green"><span className="dot green" /> Coder: {coderName}</span>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" }}>
              <span className="chip amber"><span className="dot amber" /> Risk: {risk}</span>
              <span className="chip blue">Mode: {mode}</span>
            </div>
          </div>
        </div>
        <div style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
          {["matrix-maintainer", "SelfRepair", "GitPilot", "MatrixLab", "OllaBridge"].map((n, i, a) => (
            <React.Fragment key={n}>
              <span className="chip" style={{ height: 26 }}>{n}</span>
              {i < a.length - 1 && <OI d={O.chevr} size={13} style={{ color: "var(--ink-4)" }} />}
            </React.Fragment>
          ))}
        </div>
      </div>

      <CoderTabs active={tab} set={setTab} />

      {tab === "pipeline" && (
        <div className="rise">
          <div className="panel" style={{ marginBottom: 22 }}>
            <div className="panel-h"><h3>GitPilot repair loop</h3><span className="chip green"><span className="dot green pulse" /> {mode} active</span></div>
            <div style={{ display: "flex", alignItems: "stretch", gap: 0, flexWrap: "wrap" }}>
              {stages.map((s, i) => (
                <React.Fragment key={s.k}>
                  <div style={{ flex: "1 1 130px", minWidth: 0, borderRadius: "var(--r-md)", padding: 15,
                    border: "1px solid " + (s.st === "todo" ? "var(--line)" : s.st === "active" ? "var(--amber-line)" : "var(--blue-line)"),
                    background: s.st === "active" ? "var(--amber-soft)" : "rgba(255,255,255,0.02)" }}>
                    <span className={"ico tone-" + (s.st === "todo" ? "blue" : s.st === "active" ? "amber" : "green")} style={{ width: 34, height: 34 }}><OI d={s.ic} size={15} /></span>
                    <div style={{ marginTop: 11, fontSize: 14, fontWeight: 600 }}>{s.k}</div>
                    <div style={{ marginTop: 3, fontSize: 11, color: "var(--ink-3)" }}>{s.o}</div>
                    <div className="mono" style={{ marginTop: 7, fontSize: 10.5, color: "var(--ink-4)" }}>{s.m}</div>
                    <div style={{ marginTop: 9 }}><span className={"chip " + (s.st === "done" ? "green" : s.st === "active" ? "amber" : "")} style={{ height: 22 }}>{s.st === "done" ? "complete" : s.st === "active" ? "waiting" : "pending"}</span></div>
                  </div>
                  {i < stages.length - 1 && <div style={{ display: "flex", alignItems: "center", padding: "0 4px", color: "var(--ink-4)" }}><OI d={O.chevr} size={16} /></div>}
                </React.Fragment>
              ))}
            </div>
          </div>
          <Panel title="GitPilot crew & repair mode">
            <div style={{ display: "flex", flexWrap: "wrap", gap: 16, alignItems: "center", justifyContent: "space-between" }}>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {[["Explorer", "Context"], ["Planner", "Strategy"], ["Coder", "Execution"], ["Reviewer", "Quality"]].map(([a, role]) => (
                  <span key={a} className="chip" style={{ height: 28 }}><span className="dot blue" /> {a} <span style={{ color: "var(--ink-4)" }}>· {role}</span></span>
                ))}
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 9 }}>
                <span className="mono" style={{ fontSize: 11, color: "var(--ink-4)" }}>REPAIR MODE</span>
                <div style={{ display: "flex", gap: 3, padding: 3, borderRadius: 99, border: "1px solid var(--line-2)", background: "rgba(0,0,0,0.3)" }}>
                  {["dry_run", "draft_pr", "apply"].map((m) => (
                    <span key={m} className="chip mono" style={{ height: 26, border: "none", background: m === mode ? "var(--blue-soft)" : "transparent", color: m === mode ? "var(--blue-2)" : "var(--ink-3)" }}>{m}</span>
                  ))}
                </div>
              </div>
            </div>
          </Panel>
        </div>
      )}

      {tab === "changes" && (
        <div className="rise" style={{ display: "flex", flexDirection: "column", gap: 22 }}>
          <Panel title="Proposed changes" link="View diff">
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {diff.map((d) => (
                <div key={d[0]} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "11px 13px", borderRadius: "var(--r-md)", border: "1px solid var(--line)", background: "rgba(255,255,255,0.02)" }}>
                  <span className="mono" style={{ fontSize: 12.5, color: "var(--ink-2)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{d[0]}</span>
                  <span className={"chip " + d[2]} style={{ flexShrink: 0 }}>{d[1]}</span>
                </div>
              ))}
            </div>
          </Panel>
          <Panel title="Sandbox result">
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
              <span className="chip green"><span className="dot green" /> exit code 0</span>
              <span className="chip">MatrixLab</span>
              <span className="chip">network disabled</span>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
              {[["Runtime", "python-3.11 · node-20"], ["Duration", "2m 14s"], ["Artifacts", "7 captured"], ["Egress", "0 attempts"]].map(([k, v]) => (
                <div key={k} style={{ padding: "11px 13px", borderRadius: "var(--r-md)", border: "1px solid var(--line)", background: "rgba(255,255,255,0.02)" }}>
                  <div style={{ fontSize: 11, color: "var(--ink-4)" }}>{k}</div>
                  <div className="mono" style={{ fontSize: 12.5, color: "var(--ink)", marginTop: 4 }}>{v}</div>
                </div>
              ))}
            </div>
          </Panel>
        </div>
      )}

      {tab === "approval" && (
        <div className="rise panel" style={{ borderColor: "var(--amber-line)", maxWidth: 640 }}>
          <div className="panel-h"><h3>Guardian decision</h3><span className="chip amber"><span className="dot amber pulse" /> Pending</span></div>
          <div style={{ fontSize: 13, color: "var(--ink-2)", lineHeight: 1.6 }}>Approval required because:</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 7, margin: "12px 0 16px" }}>
            {[["source code modified", true], ["unit tests passed", true], ["secret scan clean", true], ["deployment blocked without human review", false]].map(([t, ok]) => (
              <div key={t} style={{ display: "flex", alignItems: "center", gap: 9, fontSize: 12.5, color: "var(--ink-2)" }}>
                <OI d={ok ? O.check : O.shield} size={14} style={{ color: ok ? "var(--blue-2)" : "#fbbf4d" }} /> {t}
              </div>
            ))}
          </div>
          <button className="deploy" style={{ width: "100%", height: 46, marginBottom: 9 }}><OI d={O.check} size={16} /> Approve PR</button>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 9 }}>
            <button className="navitem" style={{ justifyContent: "center", border: "1px solid var(--line-2)", fontSize: 13 }}>Request changes</button>
            <button className="navitem" style={{ justifyContent: "center", border: "1px solid var(--red-line)", color: "#ff8585", fontSize: 13 }}>Reject</button>
          </div>
          <button className="navitem" style={{ justifyContent: "center", width: "100%", marginTop: 9, border: "1px solid var(--line)", fontSize: 12.5, color: "var(--ink-3)" }}>Escalate to security</button>
        </div>
      )}

      {tab === "evidence" && (
        <div className="rise panel" style={{ maxWidth: 640 }}>
          <div className="panel-h"><h3>Evidence bundle</h3><span className="chip amber">1 pending</span></div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {evidence.map((e) => {
              const ok = e[1] !== "pending";
              return (
                <div key={e[0]} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 13px", borderRadius: "var(--r-md)", border: "1px solid var(--line)", background: "rgba(255,255,255,0.02)" }}>
                  <span className="mono" style={{ fontSize: 12, color: "var(--ink-2)" }}>{e[0]}</span>
                  <span style={{ display: "inline-flex", alignItems: "center", gap: 7, fontSize: 12, color: ok ? "var(--blue-2)" : "#fbbf4d" }}>
                    <OI d={ok ? O.check : O.gauge} size={13} /> {e[1]}
                  </span>
                </div>
              );
            })}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1.4fr 1fr", gap: 9, marginTop: 14 }}>
            <button className="deploy" style={{ height: 42, background: "var(--blue-soft)", color: "var(--blue-2)", border: "1px solid var(--blue-line)", boxShadow: "none" }}><OI d={O.eye} size={15} /> Review evidence</button>
            <button className="navitem" style={{ justifyContent: "center", border: "1px solid var(--line-2)", fontSize: 13 }}>Download</button>
          </div>
        </div>
      )}

      {tab === "autonomy" && (
        <div className="rise panel" style={{ maxWidth: 720 }}>
          <div className="panel-h"><h3>Autonomy rollout stage</h3></div>
          <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
            {rollout.map((r, i) => (
              <div className="setrow" key={r[0]}>
                <div style={{ display: "flex", alignItems: "center", gap: 13, minWidth: 0 }}>
                  <span className="mono" style={{ fontSize: 12, color: "var(--ink-4)", width: 14 }}>{i + 1}</span>
                  <div><div style={{ fontSize: 13.5, fontWeight: 600 }}>{r[0]}</div>
                    <div style={{ fontSize: 11.5, color: "var(--ink-3)", marginTop: 2 }}>{r[1]}{r[4] && <span style={{ color: "var(--ink-4)" }}> · {r[4]}</span>}</div></div>
                </div>
                <span className={"chip " + r[3]} style={{ flexShrink: 0 }}><span className={"dot " + r[3]} /> {r[2]}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </React.Fragment>
  );
}

function Placeholder({ label, go }) {
  return (
    <div className="panel rise" style={{ display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center", padding: 60 }}>
      <span style={{ color: "var(--blue)", opacity: 0.5 }}><OI d={O.spark} size={38} /></span>
      <h2 style={{ margin: "16px 0 0", fontSize: 20 }}>{label}</h2>
      <p style={{ margin: "8px 0 0", fontSize: 13.5, color: "var(--ink-3)", maxWidth: 420, lineHeight: 1.6 }}>
        This module is part of the Matrix OS command center. The Overview is the live demo surface — {label} follows the same shell and component system.
      </p>
      <button className="deploy" style={{ marginTop: 20 }} onClick={() => go("overview")}><OI d={O.grid} size={16} /> Back to Overview</button>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("os-root")).render(<App />);
